import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SideMenu } from '@/components/Sidemenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='min-h-screen bg-white'>
          <div className='lg:flex h-dvh'>
            <SideMenu className='relative hidden lg:flex' />
            <div className='flex flex-1'>{children}</div>
          </div>
        </main>
      </body>
    </html>
  )
}
